#ifndef JSONREPAIR_H
#define JSONREPAIR_H

/* Generated with cbindgen:0.27.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace jsonrepair {
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace jsonrepair
#endif  // __cplusplus

#endif  /* JSONREPAIR_H */
